# Generated by Django 4.2.6 on 2024-01-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatriculasWATT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignaturawatt',
            old_name='cursoWATT',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='cursowatt',
            old_name='carreraWATT',
            new_name='carrera',
        ),
    ]
