# Generated by Django 4.2.6 on 2024-01-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatriculasWATT', '0003_alter_asignaturawatt_curso_alter_cursowatt_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturawatt',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MatriculasWATT.cursowatt'),
        ),
        migrations.AlterField(
            model_name='cursowatt',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MatriculasWATT.carrerawatt'),
        ),
    ]
